apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: text-clf-infer
spec:
  version: "v1.0.0"
  image: "lizzzcai/text-clf-infer-func:v0.6.0"
  imageCredentials:
    name: push-secret
  port: 8080
  build:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 3
    timeout: 10m
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "predict"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "infer_scikit.py"
    srcRepo:
      url: "https://github.com/lizzzcai/openfunction-samples.git"
      sourceSubPath: "text-classification/python"
      revision: "main"
  serving:
    runtime: knative
    labels:
      app: openfunction
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
      autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m"
      autoscaling.knative.dev/metric: "concurrency" # concurrency, rps, cpu, memory
      autoscaling.knative.dev/target: "2" # metric agnostic
      autoscaling.knative.dev/target-utilization-percentage: "80"
      #autoscaling.knative.dev/min-scale: "0"
      autoscaling.knative.dev/initial-scale: "1"
      #autoscaling.knative.dev/max-scale: "3"
      autoscaling.knative.dev/scale-down-delay: "10m"
      autoscaling.knative.dev/window: 60s
    scaleOptions:
      knative:
        #autoscaling.knative.dev/min-scale: "0"
        #autoscaling.knative.dev/max-scale: "2"
      maxReplicas: 3
      minReplicas: 0
    template:
      volumes:
      - name: classifier-provision-location
        emptyDir: {}

      initContainers:
      - name: storage-initializer
        image: seldonio/rclone-storage-initializer:1.14.0-dev
        imagePullPolicy: Always
        args:
          - "s3://<bucket>/<path>/models"
          - "/mnt/models"

        volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

        envFrom:
          - secretRef:
              name: seldon-init-container-secret

      containers:
        - name: function
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt/models
              name: classifier-provision-location
              readOnly: true