apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: iris-python
spec:
  version: "v1.0.0"
  image: "lizzzcai/iris-python-func:v0.6.0"
  imageCredentials:
    name: push-secret
  port: 8080
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "predict"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "main.py"
    srcRepo:
      url: "https://github.com/lizzzcai/openfunction-samples.git"
      sourceSubPath: "iris-python"
      revision: "main"
  serving:
    runtime: knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always